### ISSUE TITLE
Subsequently to assigning metadata to an execution, does an api exist to query executions by metadata?

### ISSUE THREAD

**Issue by NMVW** [defer-run/documentation#12]
Path: /features/metadata

**Comment by NMVW** [comment]
`getExecution(executionId)` [x]
`queryExecutionsByMetadata(assignedMetadata)` []

**Comment by gearnode** [comment]
Currently not included in our SDK (coming soon). You can use our [V2 API](https://www.defer.run/docs/references/http-api/v2/execution/list-executions) :)

**Comment by gearnode** [comment]
The `@defer/client` version 2.x now includes the `listExecutions` function, which enables you to filter with metadata.
